name: ping_discover_network
description: Library that allows to ping IP subnet and discover network devices. Could be used to find printers and other devices and services in a local network.
version: 0.2.0+1
author: Andrey Ushakov <flutter@tablemi.com>
homepage: https://github.com/andrey-ushakov/ping_discover_network

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wifi:
    git: https://github.com/fishappy0/wifi_nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
